- public/landing/index.html
- public/landing/landing.styl
* dark background;
* add placeholders for description;
* add footer;
> [22] - Landing page improvements:

- public/common/stylesheets/color-palette.styl
- public/game-master/styles/game-master.styl
- public/game-master/styles/index.styl
- public/game-master/views/app-view.coffee
> Add players table styling;

- app/facets/participant/game-master.coffee
- app/facets/participant/participant-facet.coffee
- app/facets/participant/participant.coffee
- app/facets/participant/player.coffee
- app/game-session.coffee
- app/session-manager.coffee
- public/common/components/match-renderer/views/index.coffee
- public/game-master/view-models/app-viewmodel.coffee
- shared/models/game-session-command.coffee
Epic back-end refactoring :crying_cat_face: 
Implemented game session commands (only `start_round` for now) :smile_cat: 
Reconnect should also work for GM
Largely untested, expect WTFs :cat:
> Implement client reconnect :cat:

- public/game-master/styles/game-master.styl
- public/game-master/view-models/app-viewmodel.coffee
- public/game-master/views/app-view.coffee
Don't pay much attention to branch name. Showing the correct selector in the end of round has been implemented.
> Display solution in the end of puzzle;

- app/session-manager.coffee
> Rename session-facet to facet

- public/game/views/game-view.coffee
> Focus selector input automatically

- public/dom-sandbox/models/puzzle/puzzle.coffee
- public/dom-sandbox/models/puzzle/test/puzzle.spec.coffee
This is one of the "important" fixes from RSCONF :smiley_cat: 
Closing tags should never be an objective, just the opening ones.
Also fixed an existing test.
> Do not mark closing tags as objective

- public/common/stylesheets/color-palette.styl
- public/game/styles/game.styl
- public/game/views/game-view.coffee
Add overlay if the puzzle is solved correctly:
> Add success overlay;

- app/auth/base-strategy.coffee
- app/cssqd-config/constants.coffee
- app/service.coffee
- public/dom-sandbox/app.coffee
- public/dom-sandbox/index.html
> set sandbox cookies via nightmare API

- .gitignore
- app/game-session.coffee
- app/scorekeeper.coffee
- package.json
- public/common/components/toggle-list/view-models/test/toggle-list-viewmodel.spec.coffee
Minor improvements for better mood every day! 🐱
> Good stuff

- public/game-master/view-models/app-viewmodel.coffee
- public/game/view-models/app-viewmodel.coffee
This makes it possible to use the new Gunslinger `exchange` helper 🐱
> Expose Warp client for use with Gunslinger

- public/game/styles/countdown.styl
- public/game/views/countdown-view.coffee
Step 1: for now - copy-paste solution. In next PR Banned chars and input will be moved into separate components;
> Redesign countdown view: step 1

- app/game-session.coffee
- public/game-master/view-models/app-viewmodel.coffee
End-round command makes a comeback! 😸
> Add end-round command

- package.json
- public/common/components/button/styles/button.styl
- public/common/components/user-panel/styles/user-panel.styl
- public/common/stylesheets/occurrence-indicator.styl
- public/landing/landing.styl
- public/quick-login/quick-login.styl
- stylint.json
- webpack.config.coffee
Stylint rules: https://github.com/rossPatton/stylint#blocks--default-false-always--never--false-
Leading zeros: http://hey.georgie.nu/leadingzero/
> integrate stylint;

- public/game/styles/countdown.styl
- public/game/styles/game.styl
> Fix text shadows; Add input highlight;

- public/common/stylesheets/match-renderer/themes/default.styl
- public/common/stylesheets/match-renderer/themes/generator.styl
> Update code highlights;

- public/game/styles/countdown.styl
- public/game/styles/game.styl
- public/game/views/countdown-view.coffee
- public/game/views/game-view.coffee
- stylint.json
> Redesign fixes

- package.json
I think alphabetical order is more friendly (especially at 2:11 am 💤 )
> reorder npm scripts

- package.json
- public/common/components/players-list/view-models/players-list.viewmodel.coffee
- public/common/components/players-list/views/index.coffee
- public/game-master/view-models/app-viewmodel.coffee
- shared/nx/cell-functor.coffee
- shared/nx/counter-command.coffee
Simply increases the counter cell when receives a correct solution from someone
I also thought "Solved" is a bit better than "Passed" which sounds like a test reporter or something 🐱
> Implement naive solvers counter

- app/game-session.coffee
- package.json
> Fix updating score

- public/game/styles/disconnected.styl
- public/game/styles/index.styl
- public/game/view-models/app-viewmodel.coffee
- public/game/views/app-view.coffee
- public/game/views/countdown-view.coffee
- public/game/views/disconnected-view.coffee
- shared/models/round-phase.coffee
Partial (quick?) fix for https://github.com/DaQuirm/css-quickdraw-redux/issues/183
> Add game disconnected view;

- public/game-master/styles/game-master.styl
Fix https://github.com/DaQuirm/css-quickdraw-redux/issues/181
> Show correct solution on hover;

- public/common/components/players-list/view-models/players-list.viewmodel.coffee
Fix https://github.com/DaQuirm/css-quickdraw-redux/issues/180
> Fix solved solutions calculation;

- bower.json
- package.json
> Get Warp from the cssconf-budapest branch

- app/session-manager.coffee
Wait for DaQuirm/nexus-warp#3 merge
> reject sessions without cookies

- public/common/components/match-renderer/views/attrs-view.coffee
Fix https://github.com/DaQuirm/css-quickdraw-redux/issues/220
> Fix #220 - Show attrs without empty values;

- public/game-master/styles/game-master.styl
- public/game-master/view-models/app-viewmodel.coffee
> Increase GM countdown;
